config/routes.rb
RelatorioFinanceiro::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :about

  resources :sessions

  resources :users

  resources :contas

  resources :relatorios

  root :to => "relatorios#index"

end

app/models/conta.rb
class Conta < ActiveRecord::Base
  belongs_to :relatorio
  validates :nome, :presence => true
  validates :valor, :presence => true, :numericality => {}
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  before_filter :login_required
  # GET /contas
  # GET /contas.xml
  def index
    @contas = Conta.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contas }
    end
  end

  # GET /contas/1
  # GET /contas/1.xml
  def show
    @conta = Conta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @conta }
    end
  end

  # GET /contas/new
  # GET /contas/new.xml
  def new
    @conta = Conta.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @conta }
    end
  end

  # GET /contas/1/edit
  def edit
    @conta = Conta.find(params[:id])
  end

  # POST /contas
  # POST /contas.xml
  def create
    @conta = Conta.new(params[:conta])

    respond_to do |format|
      if @conta.save
        format.html { redirect_to(@conta, :notice => 'Conta was successfully created.') }
        format.xml  { render :xml => @conta, :status => :created, :location => @conta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contas/1
  # PUT /contas/1.xml
  def update
    @conta = Conta.find(params[:id])

    respond_to do |format|
      if @conta.update_attributes(params[:conta])
        format.html { redirect_to(@conta, :notice => 'Conta was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @conta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1
  # DELETE /contas/1.xml
  def destroy
    @conta = Conta.find(params[:id])
    @conta.destroy

    respond_to do |format|
      format.html { redirect_to(contas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/views/contas/_form.html.erb
<%= form_for(@conta) do |f| %>
  <% if @conta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conta.errors.count, "error") %> prohibited this conta from being saved:</h2>

      <ul>
      <% @conta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :relatorio_id %><br />
    <%= f.collection_select(:relatorio_id, Relatorio.order(:ano), :id, :print_month, {:prompt => true}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contas/edit.html.erb
<h1>Editar Conta</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @conta %> |
<%= link_to 'Voltar', contas_path %>

app/views/contas/index.html.erb
<h1>Lista de Contas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Valor</th>
    <th>Relatório</th>
  </tr>

<% @contas.each do |conta| %>
  <tr>
    <td><%= conta.nome %></td>
    <td><%= conta.valor %></td>
    <td><%= conta.relatorio.mes.strftime("%B") %></td>
    <td><%= link_to 'Exibir', conta %></td>
    <td><%= link_to 'Editar', edit_conta_path(conta) %></td>
    <td><%= link_to 'Apagar', conta, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Criar Conta', new_conta_path %>

app/views/contas/new.html.erb
<h1>Nova conta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', contas_path %>

app/views/contas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @conta.nome %>
</p>

<p>
  <b>Valor:</b>
  <%= @conta.valor %>
</p>

<p>
  <b>Relatorio:</b>
  <%= @conta.relatorio.mes.strftime("%B") %>
</p>


<%= link_to 'Editar', edit_conta_path(@conta) %> |
<%= link_to 'Voltar', contas_path %>