config/routes.rb
RelatorioFinanceiro::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :about

  resources :sessions

  resources :users

  resources :contas

  resources :relatorios

  root :to => "relatorios#index"

end

app/models/relatorio.rb
class Relatorio < ActiveRecord::Base
  has_many :contas
  validates :mes, :presence => true
  validates :ano, :presence => true
  validates :saldo_mes_anterior, :presence => true, :numericality => {}
  validates :dizimos, :presence => true, :numericality => {}
  validates :ofertas, :presence => true, :numericality => {}

  def print_month
    month = self.mes.strftime("%B")
    year = self.ano.strftime("%Y")
    return "#{month} / #{year}"
  end
end

app/controllers/relatorios_controller.rb
class RelatoriosController < ApplicationController
  before_filter :login_required, :except => [:index, :show]
  respond_to :js
  # GET /relatorios
  # GET /relatorios.xml
  def index
    @relatorios = Relatorio.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @relatorios }
    end
  end

  # GET /relatorios/1
  # GET /relatorios/1.xml
  def show
    @conta = Conta.new
    @relatorio = Relatorio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @relatorio }
    end
  end

  # GET /relatorios/new
  # GET /relatorios/new.xml
  def new
    @relatorio = Relatorio.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @relatorio }
    end
  end

  # GET /relatorios/1/edit
  def edit
    @relatorio = Relatorio.find(params[:id])
  end

  # POST /relatorios
  # POST /relatorios.xml
  def create
    @relatorio = Relatorio.new(params[:relatorio])

    respond_to do |format|
      if @relatorio.save
        format.html { redirect_to(@relatorio, :notice => 'Relatorio was successfully created.') }
        format.xml  { render :xml => @relatorio, :status => :created, :location => @relatorio }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @relatorio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /relatorios/1
  # PUT /relatorios/1.xml
  def update
    @relatorio = Relatorio.find(params[:id])

    respond_to do |format|
      if @relatorio.update_attributes(params[:relatorio])
        format.html { redirect_to(@relatorio, :notice => 'Relatorio was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @relatorio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /relatorios/1
  # DELETE /relatorios/1.xml
  def destroy
    @relatorio = Relatorio.find(params[:id])
    @relatorio.destroy

    respond_with @relatorio
  end
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/relatorios/_form.html.erb
<%= form_for(@relatorio) do |f| %>
  <% if @relatorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relatorio.errors.count, "error") %> prohibited this relatorio from being saved:</h2>

      <ul>
      <% @relatorio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mes, "Mês" %><br />
    <%= f.date_select :mes, :discard_day => true, :discard_year => true %>
  </div>
  <div class="field">
    <%= f.label :ano %><br />
    <%= f.date_select :ano, :discard_day => true, :discard_month => true %>
  </div>
  <div class="field">
    <%= f.label :saldo_mes_anterior, "Saldo do Mês Anterior" %><br />
    <%= f.text_field :saldo_mes_anterior %>
  </div>
  <div class="field">
    <%= f.label :dizimos, "Dízimos" %><br />
    <%= f.text_field :dizimos %>
  </div>
  <div class="field">
    <%= f.label :ofertas %><br />
    <%= f.text_field :ofertas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relatorios/edit.html.erb
<h1>Editar Relatório</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @relatorio %> |
<%= link_to 'Voltar', relatorios_path %>

app/views/relatorios/index.html.erb
<h2>Lista de Relatórios</h2>

<table>
  <tr>
    <th>Mês</th>
    <th>Ano</th>
    <th>Saldo do Mês Anterior</th>
    <th>Dizimos</th>
    <th>Ofertas</th>
  </tr>

<% @relatorios.each do |relatorio| %>
  <tr>
    <td><%= relatorio.mes.strftime("%B") %></td>
    <td><%= relatorio.ano.strftime("%Y") %></td>
    <td><%= valor_formatado(relatorio.saldo_mes_anterior) %></td>
    <td><%= valor_formatado(relatorio.dizimos) %></td>
    <td><%= valor_formatado(relatorio.ofertas) %></td>
    <td><%= link_to 'Mostrar', relatorio %></td>
    <% if logged_in? -%>
      <td><%= link_to 'Editar', edit_relatorio_path(relatorio) %></td>
      <td><%= link_to 'Apagar', relatorio, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end -%>
  </tr>
<% end %>
</table>

<br />
<% if logged_in? -%>
  <%= link_to 'Criar Relatório', new_relatorio_path %>
<% end -%>

app/views/relatorios/new.html.erb
<h1>Novo Relatório</h1>

<%= render 'form' %>

<%= link_to 'Voltar', relatorios_path %>

app/views/relatorios/show.html.erb
<h2>Relatório Financeiro</h2>
<p id="notice"><%= notice %></p>

<p>
  <b>Mês:</b> <%= @relatorio.mes.strftime("%B") %> | <b>Ano:</b> <%= @relatorio.ano.strftime("%Y") %>
</p>

<p>
  <b>Saldo do Mês Anterior:</b>
  <%= valor_formatado(@relatorio.saldo_mes_anterior) %>
</p>

<p>
  <b>Dízimos:</b> <%= valor_formatado(@relatorio.dizimos) %> | <b>Ofertas:</b> <%= valor_formatado(@relatorio.ofertas) %>
</p>

<% entradas = @relatorio.saldo_mes_anterior + @relatorio.dizimos + @relatorio.ofertas -%>
<p><b>Total de Entradas:</b> <%= valor_formatado(entradas) %></p>

<hr />

<h3>Contas do mês de <%= @relatorio.mes.strftime("%B") %></h3>
<% saida = 0.0 -%>
<% @relatorio.contas.each do |conta|-%>
  <% saida += conta.valor -%>
  <p>
    <b>Conta:</b> <%= conta.nome %> | <b>Valor:</b> <%= valor_formatado(conta.valor) %>
  </p>
<% end -%>

<p><b>Total de Saídas:</b> <%= valor_formatado(saida) %></p>

<hr />

<p><b>Saldo para o próximo mês:</b> <%= valor_formatado(entradas - saida) %></p>

<% if logged_in? -%>
  <%= link_to 'Editar', edit_relatorio_path(@relatorio) %> |
<% end -%>
<%= link_to 'Voltar', relatorios_path %>